wall_patch_planner:
  ros__parameters:
    cloud_topic: /interior_wall/wall_planes_cloud
    camera_info_topic: /camera/camera_info
    output_pose_topic: /wall_patch_planner/poses
    output_debug_cloud_topic: /wall_patch_planner/debug_cloud
    output_marker_topic: /wall_patch_planner/debug_markers
    world_frame: map
    camera_frame_prefix: wall_patch
    selected_room_id: 1
    selected_wall_ids: [3]
    plane_label_stride: 1000
    fov_distance: 0.30
    wall_distance: 0.05
    overlap: 0.0
    ee_size_x: 0.30
    ee_size_y: 0.30
    grid_resolution: 0.05
    min_valid_roi_ratio: 0.4
    min_new_coverage_ratio: 0.003
    roi_width_px: 512.0
    roi_height_px: 512.0
    roi_center_u_offset_px: 0.0
    roi_center_v_offset_px: 0.0
    max_tf_frames: 512
