world_pointcloud_generator:
  ros__parameters:
    world_sdf_path: ''
    frame_id: map
    topic_name: /synthetic_world/points
    resolution: 0.10
    surface_mode: interior_vertical
    include_floor_and_ceiling: false
    bbox_min: [-20.0, -20.0, -2.0]
    bbox_max: [20.0, 20.0, 10.0]
    publish_period_sec: 1.0
    auto_generate_on_startup: true
    auto_save_pcd: false
    pcd_path: world_scan.pcd
    auto_save_nav2_map: false
    nav2_map_yaml_path: world_scan_nav2.yaml
    nav2_map_resolution: 0.05
    use_nav2_map_height_slice: false
    nav2_map_slice_height: 1.0
    nav2_map_slice_thickness: 0.20
