bool enable_clustering
float32 voxel_size_m
float32 neighbor_distance_m
uint32 min_cluster_points
---
bool success
string status_code
string message
uint32 raw_entry_count
uint32 map_entry_count
bool clustering_applied
