string image_id
uint32[] shot_ids
sensor_msgs/Image roi_rgb_processed
float32 score_threshold_override
---
bool success
string status_code
string message
defect_map_interfaces/SegmentedInstance[] instances
